# # Gunakan Node.js 18
# FROM node:18

# # Set working directory di container
# WORKDIR /app

# # Copy package.json & package-lock.json dari folder vue-app
# COPY vue-app/package*.json ./

# # Install dependencies di container
# RUN npm install

# # Copy semua source code dari folder vue-app
# COPY . .

# # Expose port Vite dev server
# EXPOSE 5173

# # Jalankan Vite dev server
# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

FROM node:22

WORKDIR /app

# copy package.json saja
COPY package*.json ./

RUN npm install

# copy source code tanpa node_modules (sudah di-ignore di .dockerignore)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
